spring:
  application:
    name: demo

  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}

    mcp:
      client:
        name: spring-ai-mcp-client
        version: 1.0.0
        toolcallback:
          enabled: true
        streamable-http:
          connections:
            mcp-server:
              url: http://localhost:8080/mcp

server:
  port: 8181